apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: astrbot-registry

resources:
  - namespace.yaml
  - configmap.yaml
  - postgres.yaml
  - redis.yaml
  - seaweedfs.yaml
  - clamav.yaml
  - backend.yaml
  - worker.yaml
  - dashboard.yaml
  - ingress.yaml

images:
  - name: ghcr.io/rc-chn/astrbot-community-plugin-registry-backend
    newTag: latest
  - name: ghcr.io/rc-chn/astrbot-community-plugin-registry-worker
    newTag: latest
  - name: ghcr.io/rc-chn/astrbot-community-plugin-registry-dashboard
    newTag: latest
  - name: clamav/clamav
    newTag: stable
